# Nombre de la aplicación
spring.application.name=proyecto-final

# Configuración H2 persistente (archivo en disco)
# spring.datasource.url=jdbc:h2:file:C:/Users/user/Documents/00-DIGITAL-HOUSE-ONE/19-Desafío-Profesional/Proyecto-Final/BDH2/db_proyecto_final
# Configuración H2 no persistente (en memoria de la JVM). BD se reinicia en cada arranque.
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Habilitar consola web de H2 para inspeccionar datos
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuración JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Muestra las consultas SQL en consola
spring.jpa.show-sql=true

# Logging de SQL (opcional, útil para debug)
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Puerto del servidor (opcional)
server.port=8080
server.address=0.0.0.0

spring.profiles.active=prod

# Configuración para el envío de correos electrónicos con Mailtrap (.env)
spring.mail.host=${MAIL_HOST:sandbox.smtp.mailtrap.io}
spring.mail.port=${MAIL_PORT:2525}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.allowed.origins=${ALLOWED_ORIGINS:}

# valores para CLIENT, ADMIN, TEST
app.frontend.client-reset-url=http://localhost:5173/reset-password
app.frontend.admin-reset-url=http://localhost:5174/reset-password
app.frontend.test-reset-fallback=http://localhost:5173/reset-password

app.frontend.client-login-url=http://localhost:5173/login
app.frontend.admin-login-url=http://localhost:5174
app.frontend.test-login-fallback=http://localhost:5173/login
