// Datos mock expandidos para productos con todas las características necesarias
export const productos = [
  {
    id: 1,
    nombre: "Toyota Corolla 2024",
    categoria: "sedan",
    precio: 45,
    pasajeros: 5,
    ubicacion: "Buenos Aires",
    imagen: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?q=80&w=400",
    disponible: true,
    transmision: "manual",
    combustible: "nafta",
    aireAcondicionado: true,
    gps: false,
    rating: 4.2,
    reviews: 127,
    caracteristicas: ["Aire acondicionado", "Radio AM/FM", "Bluetooth", "USB"],
    marca: "Toyota",
    año: 2024,
    cilindrada: 1.8,
    consumo: 7.2, // L/100km
    disponibilidadEspecial: []
  },
  {
    id: 2,
    nombre: "Honda Civic Hybrid",
    categoria: "sedan",
    precio: 55,
    pasajeros: 5,
    ubicacion: "Córdoba",
    imagen: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?q=80&w=400",
    disponible: true,
    transmision: "automatica",
    combustible: "hibrido",
    aireAcondicionado: true,
    gps: true,
    rating: 4.5,
    reviews: 89,
    caracteristicas: ["Aire acondicionado", "GPS", "Cámara trasera", "Bluetooth", "USB", "Android Auto"],
    marca: "Honda",
    año: 2023,
    cilindrada: 2.0,
    consumo: 5.8,
    disponibilidadEspecial: []
  },
  {
    id: 3,
    nombre: "Toyota Camry Premium",
    categoria: "sedan",
    precio: 75,
    pasajeros: 5,
    ubicacion: "Buenos Aires",
    imagen: "https://images.unsplash.com/photo-1616788874313-95c6de7d91d4?q=80&w=400",
    disponible: true,
    transmision: "automatica",
    combustible: "nafta",
    aireAcondicionado: true,
    gps: true,
    rating: 4.7,
    reviews: 203,
    caracteristicas: ["Aire acondicionado", "GPS", "Asientos de cuero", "Bluetooth", "Cámara 360°", "Techo solar"],
    marca: "Toyota",
    año: 2024,
    cilindrada: 2.5,
    consumo: 8.1,
    disponibilidadEspecial: []
  },
  {
    id: 4,
    nombre: "Volkswagen Gol Trend",
    categoria: "hatchback",
    precio: 35,
    pasajeros: 5,
    ubicacion: "La Plata",
    imagen: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?q=80&w=400",
    disponible: true,
    transmision: "manual",
    combustible: "nafta",
    aireAcondicionado: true,
    gps: false,
    rating: 3.9,
    reviews: 156,
    caracteristicas: ["Aire acondicionado", "Radio AM/FM", "USB"],
    marca: "Volkswagen",
    año: 2023,
    cilindrada: 1.6,
    consumo: 6.9,
    disponibilidadEspecial: []
  },
  {
    id: 5,
    nombre: "Toyota RAV4 Adventure",
    categoria: "suv",
    precio: 85,
    pasajeros: 7,
    ubicacion: "Buenos Aires",
    imagen: "https://images.unsplash.com/photo-1606813907291-d86efa9b94db?q=80&w=400",
    disponible: true,
    transmision: "automatica",
    combustible: "nafta",
    aireAcondicionado: true,
    gps: true,
    rating: 4.6,
    reviews: 174,
    caracteristicas: ["Aire acondicionado", "GPS", "4x4", "Bluetooth", "Cámara trasera", "Control crucero"],
    marca: "Toyota",
    año: 2024,
    cilindrada: 2.5,
    consumo: 9.2,
    disponibilidadEspecial: []
  },
  {
    id: 6,
    nombre: "Ford Explorer XLT",
    categoria: "suv",
    precio: 95,
    pasajeros: 8,
    ubicacion: "Mendoza",
    imagen: "https://images.unsplash.com/photo-1606813907291-d86efa9b94db?q=80&w=400",
    disponible: true,
    transmision: "automatica",
    combustible: "nafta",
    aireAcondicionado: true,
    gps: true,
    rating: 4.4,
    reviews: 98,
    caracteristicas: ["Aire acondicionado", "GPS", "4x4", "Asientos de cuero", "Bluetooth", "Apple CarPlay", "3ra fila"],
    marca: "Ford",
    año: 2023,
    cilindrada: 3.5,
    consumo: 11.5,
    disponibilidadEspecial: []
  },
  {
    id: 7,
    nombre: "Ford F-150 Raptor",
    categoria: "pickup",
    precio: 120,
    pasajeros: 5,
    ubicacion: "Salta",
    imagen: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?q=80&w=400",
    disponible: true,
    transmision: "automatica",
    combustible: "nafta",
    aireAcondicionado: true,
    gps: true,
    rating: 4.8,
    reviews: 67,
    caracteristicas: ["Aire acondicionado", "GPS", "4x4", "Asientos deportivos", "Bluetooth", "Barra LED", "Gancho remolque"],
    marca: "Ford",
    año: 2024,
    cilindrada: 3.5,
    consumo: 13.2,
    disponibilidadEspecial: []
  },
  {
    id: 8,
    nombre: "BMW Z4 sDrive30i",
    categoria: "convertible",
    precio: 180,
    pasajeros: 2,
    ubicacion: "Mar del Plata",
    imagen: "https://images.unsplash.com/photo-1603384696015-871af6a62b49?q=80&w=400",
    disponible: true,
    transmision: "automatica",
    combustible: "nafta",
    aireAcondicionado: true,
    gps: true,
    rating: 4.9,
    reviews: 34,
    caracteristicas: ["Aire acondicionado", "GPS", "Techo convertible", "Asientos de cuero", "Bluetooth", "Sistema premium", "Modo sport"],
    marca: "BMW",
    año: 2024,
    cilindrada: 2.0,
    consumo: 8.7,
    disponibilidadEspecial: []
  },
  {
    id: 9,
    nombre: "Mercedes-Benz C300 Coupe",
    categoria: "coupe",
    precio: 200,
    pasajeros: 4,
    ubicacion: "Rosario",
    imagen: "https://images.unsplash.com/photo-1555215695-3004980ad54e?q=80&w=400",
    disponible: true,
    transmision: "automatica",
    combustible: "nafta",
    aireAcondicionado: true,
    gps: true,
    rating: 4.8,
    reviews: 52,
    caracteristicas: ["Aire acondicionado", "GPS", "Asientos de cuero", "Bluetooth", "Sistema multimedia", "Llantas deportivas", "Iluminación LED"],
    marca: "Mercedes-Benz",
    año: 2024,
    cilindrada: 2.0,
    consumo: 9.1,
    disponibilidadEspecial: []
  },
  {
    id: 10,
    nombre: "Chevrolet Onix Premier",
    categoria: "hatchback",
    precio: 40,
    pasajeros: 5,
    ubicacion: "Tucumán",
    imagen: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?q=80&w=400",
    disponible: true,
    transmision: "automatica",
    combustible: "nafta",
    aireAcondicionado: true,
    gps: true,
    rating: 4.1,
    reviews: 143,
    caracteristicas: ["Aire acondicionado", "GPS", "Bluetooth", "USB", "MyLink", "Cámara trasera"],
    marca: "Chevrolet",
    año: 2023,
    cilindrada: 1.0,
    consumo: 6.5,
    disponibilidadEspecial: []
  },
  {
    id: 11,
    nombre: "Jeep Compass Limited",
    categoria: "suv",
    precio: 110,
    pasajeros: 5,
    ubicacion: "Neuquén",
    imagen: "https://images.unsplash.com/photo-1606813907291-d86efa9b94db?q=80&w=400",
    disponible: true,
    transmision: "automatica",
    combustible: "nafta",
    aireAcondicionado: true,
    gps: true,
    rating: 4.3,
    reviews: 87,
    caracteristicas: ["Aire acondicionado", "GPS", "4x4", "Asientos de cuero", "Bluetooth", "Uconnect", "Techo panorámico"],
    marca: "Jeep",
    año: 2023,
    cilindrada: 2.4,
    consumo: 10.1,
    disponibilidadEspecial: []
  },
  {
    id: 12,
    nombre: "Fiat Cronos Drive",
    categoria: "sedan",
    precio: 38,
    pasajeros: 5,
    ubicacion: "San Juan",
    imagen: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?q=80&w=400",
    disponible: true,
    transmision: "manual",
    combustible: "nafta",
    aireAcondicionado: true,
    gps: false,
    rating: 3.7,
    reviews: 92,
    caracteristicas: ["Aire acondicionado", "Radio AM/FM", "USB", "Bluetooth"],
    marca: "Fiat",
    año: 2023,
    cilindrada: 1.3,
    consumo: 7.8,
    disponibilidadEspecial: []
  },
  {
    id: 13,
    nombre: "Audi A4 Quattro",
    categoria: "sedan",
    precio: 160,
    pasajeros: 5,
    ubicacion: "Buenos Aires",
    imagen: "https://images.unsplash.com/photo-1616788874313-95c6de7d91d4?q=80&w=400",
    disponible: false, // No disponible para probar filtros
    transmision: "automatica",
    combustible: "nafta",
    aireAcondicionado: true,
    gps: true,
    rating: 4.7,
    reviews: 76,
    caracteristicas: ["Aire acondicionado", "GPS", "Quattro AWD", "Asientos de cuero", "Bluetooth", "Virtual Cockpit", "Sistema premium"],
    marca: "Audi",
    año: 2024,
    cilindrada: 2.0,
    consumo: 8.9,
    disponibilidadEspecial: []
  },
  {
    id: 14,
    nombre: "Nissan Frontier Pro-4X",
    categoria: "pickup",
    precio: 105,
    pasajeros: 5,
    ubicacion: "Chaco",
    imagen: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?q=80&w=400",
    disponible: true,
    transmision: "automatica",
    combustible: "diesel",
    aireAcondicionado: true,
    gps: true,
    rating: 4.5,
    reviews: 54,
    caracteristicas: ["Aire acondicionado", "GPS", "4x4", "Bluetooth", "NissanConnect", "Gancho remolque", "Barras laterales"],
    marca: "Nissan",
    año: 2023,
    cilindrada: 2.5,
    consumo: 9.8,
    disponibilidadEspecial: []
  },
  {
    id: 15,
    nombre: "Peugeot 208 GT",
    categoria: "hatchback",
    precio: 42,
    pasajeros: 5,
    ubicacion: "Santa Fe",
    imagen: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?q=80&w=400",
    disponible: true,
    transmision: "automatica",
    combustible: "nafta",
    aireAcondicionado: true,
    gps: true,
    rating: 4.2,
    reviews: 118,
    caracteristicas: ["Aire acondicionado", "GPS", "Bluetooth", "Mirror Screen", "Cámara trasera", "Llantas deportivas"],
    marca: "Peugeot",
    año: 2023,
    cilindrada: 1.2,
    consumo: 6.3,
    disponibilidadEspecial: []
  }
];

// Utilidades para filtros
export const marcas = [...new Set(productos.map(p => p.marca))].sort();
export const categorias = [...new Set(productos.map(p => p.categoria))].sort();
export const ubicaciones = [...new Set(productos.map(p => p.ubicacion))].sort();
export const transmisiones = [...new Set(productos.map(p => p.transmision))].sort();
export const combustibles = [...new Set(productos.map(p => p.combustible))].sort();

export const precioRango = {
  min: Math.min(...productos.map(p => p.precio)),
  max: Math.max(...productos.map(p => p.precio))
};

export const pasajerosRango = {
  min: Math.min(...productos.map(p => p.pasajeros)),
  max: Math.max(...productos.map(p => p.pasajeros))
};